### PR TITLE
Anagram Exercise Response

### PR DESCRIPTION
**Pull request by amymariewall**
This is still failing the test. The error says my program is returning nil instead of true. I am wondering if perhaps I am still misunderstanding how a program "returns" values. I remember reading that puts actually returns nil, and I did use puts on my last line, so I am going to look into that.

### CODE REVIEW

**Comment by amymariewall** [comment]
That appeared to do the trick!

**Comment by sumeetjain** [comment]
Nice! This is approvable as is, but I'd like you to describe the following line of code in your own words first.

``` ruby
word_first.map {|i| word_second.include?(i) }
```

**Comment by amymariewall** [comment]
I would what I'm asking the program to do in that line as follows:

Create an array of the true/false responses (the results) that get returned when you take each letter of first array_word array and compare it to second_word array to see if second_word contains (includes) that letter.

**Comment by sumeetjain** [comment]
:+1:

**Pull request closed without merging**
