### PR TITLE
rake aborted?

### PR DESCRIPTION
**Pull request by santaclauslives**
This must not be done yet. It makes sense to me, but when I try the "rake" test, I get a "rake aborted" message along with a very long list of other text. There are no indicators beside any of the lines of code, so I am a little stumped as to what I can do to at least get through the rake test. Here again, it works in repl.it.

### CODE REVIEW

**Comment by sumeetjain** [comment]
Same as your other submission–the algorithm looks good to me. Just need to get the code encapsulated within a method.

**Comment by santaclauslives** [comment]
Thank you. I will get back to work on these.

**Comment by sumeetjain** [comment]
:+1: Nice!

Something interesting–well, interesting to _me_ :smile:– is that the `==` (comparison) operator returns `true` or `false`. So if you have this code (I labeled it so I can refer to it later):

``` ruby
if x == y # Expression
  true # Branch 1
else
  false # Branch 2
end
```

That _Expression_ is going to be either true or false–obviously, right? And then you use its value of true/false to trigger either _Branch 1_ or _Branch 2_ so that either `true` or `false` is returned.

What's totally cool [to me] is that you can just do this: `return (x == y)`–it replaces the entire block of code above! Again, the _Expression_ is either true or false to begin with, so you might as well just return that–no need for the if/then at all! :dancer: 

---

Bonus Note: Ruby is forgiving, so it'll even work without the parentheses: `return x == y` _and it'll even work without the 'return' keyword: `x == y` (because Ruby always assumes the last line of a method is meant to be the `return`. But none of this is important right now–just thought I'd mention it.

**Comment by santaclauslives** [comment]
Thank you for the information. That is a cool thing that would have saved
several lines of code. My Ruby vocabulary is so puny right now. Everything
is new.

**Pull request closed without merging**
